name: jkroepke-ansible
version: '2.5.3-1'
summary: Using Ansible w/ bundled Python without misconfigure the systems python. # 79 char long summary
description: |
  This snap is provides a predefined environment for Ansible runs. It includes some additional pip for example docker-py.

type: core
icon: snap/ansible.png
grade: devel
confinement: classic

apps:
  ansible:
    command: bin/ansible
  ansible-galaxy:
    command: bin/ansible-galaxy
  ansible-playbook:
    command: bin/ansible-playbook
  ansible-connection:
    command: bin/ansible-connection
  ansible-inventory:
    command: bin/ansible-inventory
  ansible-pull:
    command: bin/ansible-playbook
  ansible-vault:
    command: bin/ansible-vault

parts:
  requirements:
    plugin: python
    python-version: python2
    requirements: requirements.txt